version: '3.1'

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: java
      POSTGRES_DB: school_management_system
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    image: openjdk:latest
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/school_management_system
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: java
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    working_dir: /app
    command: ["sh", "-c", "./mvnw spring-boot:run"]

volumes:
  pgdata:
